---
controller:
  admin:
    username: "rafal"
  jenkinsUrlProtocol: "https"
  jenkinsUrl: "jenkins.prod-1.dev-software.pl"
agent:
  additionalContainers:
    - sideContainerName: dind
      image:
        repository: docker
        tag: dind
      command: dockerd-entrypoint.sh
      args: ""
      privileged: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
persistence:
  storageClass: nas-storage
