---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - StorageClass.yaml
  - jenkins-prod-1-pv.yaml
  - n8n-prod-1-pv.yaml
  - postgres-prod-1-pv.yaml
  - uptime-kuma-prod-1-pv.yaml
  - vault-prod-1-pv.yaml
