---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n-prod-1
data:
  N8N_EDITOR_BASE_URL: "https://n8n.prod-1.dev-software.pl/"
  WEBHOOK_URL: "https://n8n.prod-1.dev-software.pl/"
  N8N_HOST: "n8n.prod-1.dev-software.pl"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  GENERIC_TIMEZONE: "Europe/Warsaw"
  TZ: "Europe/Warsaw"
  DB_TYPE: "postgresdb"
