---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n-prod-1
resources:
  - ConfigMap.yaml
  - IngressRoute.yaml
  - Service.yaml
  - ServiceAccount.yaml
  - StatefulSet.yaml
