---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saunamaster-toolbox-backend-prod-1
  namespace: saunamaster-toolbox-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: saunamaster-toolbox-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saunamaster-toolbox-backend
  template:
    metadata:
      labels:
        app: saunamaster-toolbox-backend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: backend
        image: nexus3.prod-1.dev-software.pl:5001/saunamaster_toolbox_backend:latest
        ports:
        - containerPort: 8080
          name: http
