---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ExternalSecret-Nexus.yaml
  - ExternalSecret-backend.yaml
  - ExternalSecret-frontend.yaml
  - ConfigMap-backend.yaml
  - ConfigMap-frontend.yaml
  - Service-backend.yaml
  - Service-frontend.yaml
  - Ingress.yaml
  - Deployment-backend.yaml
  - Deployment-frontend.yaml
