apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ui-ingress
  namespace: vault-prod-1
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.prod-1.dev-software.pl`)
      kind: Rule
      services:
        - name: vault-prod-1
          port: 8200
  tls:
    secretName: prod-1-dev-software-prod-tls
