---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-prod-1
resources:
  - bind9-prod-1.yaml
  - metallb-prod-1.yaml
  - n8n-prod-1.yaml
  - postgres-prod-1.yaml
  - storage.yaml
  - uptime-kuma-prod-1.yaml
  - vault-prod-1.yaml
