
---
apiVersion: v1
kind: Service
metadata:
  name: bind9-prod-1-tcp
  namespace: bind9-prod-1
  labels:
    app: bind9
  annotations:
    metallb.io/allow-shared-ip: "bind9-prod-1"
    metallb.io/loadBalancer-ips: "10.10.255.101"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: bind9
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: dns-tcp

---
apiVersion: v1
kind: Service
metadata:
  name: bind9-prod-1-udp
  namespace: bind9-prod-1
  labels:
    app: bind9
  annotations:
    metallb.io/allow-shared-ip: "bind9-prod-1"
    metallb.io/loadBalancer-ips: "10.10.255.101"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: bind9
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: dns-udp

---
apiVersion: v1
kind: Service
metadata:
  name: bind9-prod-1-metrics
  namespace: bind9-prod-1
  labels:
    app: bind9
spec:
  type: ClusterIP
  selector:
    app: bind9
  ports:
  - name: metrics
    protocol: TCP
    port: 9119
    targetPort: metrics